name: 'Project: Release'
# shall trigger on the main branch when a tag named 'v*' gets created
on: 
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Release Build
    permissions:
      contents: read
    uses: ./.github/workflows/shared-build.yml
    with:
      store-artifacts: true
      sign-binaries: true
    secrets:
      SIGNING_CERT_PFX: ${{ secrets.SIGNING_CERT_PFX }}
      SIGNING_CERT_PASSWORD: ${{ secrets.SIGNING_CERT_PASSWORD }}
      SIGNING_CERT_THUMBPRINT: ${{ secrets.SIGNING_CERT_THUMBPRINT }}

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    if: ${{ github.ref_type == 'tag' }}

    env:
      GitHubReleaseBodyFile: ${{ github.workspace }}/src/ReleaseNotes.md

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download artifacts
      id: download
      uses: actions/download-artifact@v4
      with:
        name: binaries

    - run: echo ${{steps.download.outputs.download-path}}
    - name: Display structure of downloaded files
      run: ls -R

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
         artifacts: '${{steps.download.outputs.download-path}}/*.exe,${{steps.download.outputs.download-path}}/*.nupkg'
         bodyFile: ${{ env.GitHubReleaseBodyFile }}